### PR TITLE
API Feature with Node_Modules Issue Fixed

### PR DESCRIPTION
**Pull request by guti21js**
Fixed API node_module issues.

### CODE REVIEW

**Comment by yizongk** [comment]
Can you briefly explain what this Pull request do?

**Comment by guti21js** [comment]
It just moved the call to the backend side so the front end only has to pass the variables it needs. It also added the commit call in the backend that can be used to call commit in the front end. 
Also it acts as a foundation for any other API callas necessary therefore if you want any specific api calls I or any can use the backend code to create more calls.

**Comment by yizongk** [comment]
When npm start just the client, but not the server, and then you hit search on some repo. You will get this: https://slack-files.com/TGNSJ2PFS-FJP6TJ7TR-8daccf9aec

And also your fork is tracking node_modules for some reason
https://slack-files.com/TGNSJ2PFS-FJ9U063LK-3d60a9102a

I will take a detail look and see where it might have went wrong later today

**Comment by guti21js** [comment]
That error always occurs if you fetch without a backend to call to.  From the backend I can't send an error message since its not on. You might have to add an error conditional that renders a 404 page if you receive anything but a json in the front end.  

As for the node_modules issue. i tried to do the revert to fix the node_module issue but for some reason it messed up my whole repo to track the node-modules. I had to rebase my master because of it. I thought that fixed the issue but I guess not. let me know what I can do to fix it because the previous recommendations didn't seem to work.

**Comment by yizongk** [comment]
Thanks! I made a small change, to move the console.log(response.clone().json()); under if(response.ok). Otherwise if no response from server, that statement will crash app.

**Pull request merged**
