### PR TITLE
feat: Output the status of all Pull Requests made to a repo, as ether…

### PR DESCRIPTION
**Pull request by yizongk**
… merged or rejected

### CODE REVIEW

**Comment by yizongk** [comment]
Now under the list of PR that is outputted, it will now also tell us whether the PR was successfully merged or no.

**Comment by guti21js** [comment]
It doesn't seem to tell me wether it was merged properly or not. The following is what I am getting.  It does show pull requests but iI don't see where it is saying that it was merged properly or not. Is this the expected outocome?

image

**Comment by yizongk** [comment]
did you clone the correct branch? I think you may have clone my master branch. clone the report-merge-status branch

**Comment by guti21js** [comment]
Changed to the branch and it looks great! 
image

**Comment by yizongk** [comment]
THanks!

**Pull request merged**
