### PR TITLE
Optional fix for workflow

### PR DESCRIPTION
**Pull request by guti21js**
Added a possible change to the git workflow according to professors slides.

### CODE REVIEW

**Comment by yizongk** [comment]
We don't want to get rid of the -p option from git pull on line 43. This is to keep your branches clean. Because you will notice every now and then you have a branch called origin/old-featture-branch that no longer exists in the remote origin repo. The -p is --prune, which help your local tracker of remote branches in a clean and accurate state.

**Comment by yizongk** [comment]
Line 50 and 51
```
  git add .
  git commit -m "Message Here"
```
those two commands are part of the "...do your edits and test...". 
the two commands are trivial, so I don't think we should put it part of the workflow, because it will cloud the big picture of the actual purpose of the workflow, to fix merge conflict

**Comment by yizongk** [comment]
Line 52
```
52: git push origin feature-branch
```
Line 53-55 (Your purposed changes)
```
53: git checkout master
54: git pull upstream master
55: git push origin master
```
Line 53-55 doesn't actually fixes your merge conflict on your feature branch if there exists some merge conflict.

What you are doing here is:
52: push your feature branch to your fork
53: on your local machine, checkout to your master branch
54: update your local master branch with the remote main/original repo (possibly resolve merge conflict if there exists(for your local master branch and remote main repo) )
55: push your master branch to your fork

No where in that step did you actually fix any merge conflict with feature-branch and remote original master branch.

I would suggest the following change:
52: git checkout master
53: git pull upstream master (fix any merge conflict for local master branch)
54: git push origin master (update your remote fork's master branch)
55: git checkout feature-branch
56: git merge master (merges your master branch INTO your feature-branch, fix any merge conflict that comes up)
***Now your feature-branch has no merge conflict with the remote main/original master branch.
57: git push origin feature-branch
...make your Pull Request from your fork remote feature branch. Then after your PR is successful...
and the rest...

**Comment by yizongk** [comment]
The rest seems solid

**Comment by guti21js** [comment]
Great. Thanks for the feedback. I'll make sure to change it

**Comment by guti21js** [comment]
> Line 50 and 51
> 
> ```
>   git add .
>   git commit -m "Message Here"
> ```
> those two commands are part of the "...do your edits and test...".
> the two commands are trivial, so I don't think we should put it part of the workflow, because it will cloud the big picture of the actual purpose of the workflow, to fix merge conflict

@yizongk 

Although I know this can be considered "trivial" for us but for others it might not seem as obvious. But I also understand how it can distract from reducing merge conflicts. How about I just add a line saying "Stage your changes and commit" after "do your edits and text..." ?

**Comment by yizongk** [comment]
Ya! That is what I had in mind as well, "A cycle of staging your changes and commiting (a cycle of git add and git commit)" or something like along those time would be nice.

**Comment by yizongk** [comment]
Looks great! Thanks so much!

**Comment by yizongk** [comment]
fixes #9

**Pull request merged**
