### PR TITLE
complete makeover of how the website looks

### PR DESCRIPTION
**Pull request by mxmsunny**
Hello, everyone! I have made changes to how the website looks like. I didn't touch on the PR area because I know that is still being worked on. Here is how it currently looks like:

test

### CODE REVIEW

**Comment by guti21js** [comment]
I think this is a great start. Why are we not pulling this? @Chocolate-Spaghet

**Comment by mxmsunny** [comment]
@Chocolate-Spaghet I have updated everything to the newer icon!

**Comment by mxmsunny** [comment]
current version of website

test

**Comment by Chocolate-Spaghet** [comment]
Looks great, thank you for your contributions! 🎉

**Pull request merged**
