### PR TITLE
Added styling and instructions on how to use on the website

### PR DESCRIPTION
**Pull request by mxmsunny**
Minor styling updates for the website. Made it less strenuous for the eyes by changing the body background to a darker color that matches the header image. Also added instructions on how to use, and then added styling on the button and input box to make testing easier as well.

tempweb

### CODE REVIEW

**Comment by yizongk** [comment]
Under App.js, reportMergeStatus

I would suggest keeping the following line:
if(eachElement.state === 'open') {
      return('Open');
    }

we might need to use this as one of the metric for your scoring system. A PR is could be in three states. Open, closed(meaning failure to merge, rejected), and merged

**Comment by yizongk** [comment]
The rest looks awesome. Will do some more test tomorrow noon,

**Comment by mxmsunny** [comment]
OH i didn't notice that was deleted. Thanks for pointing it out! Will update soon.

**Comment by yizongk** [comment]
Testing done, looks good to go. Merging now

**Comment by yizongk** [comment]
Thanks!

**Pull request merged**
