### PR TITLE
Boilerplate

### PR DESCRIPTION
**Pull request by Chocolate-Spaghet**
I added a boilerplate that may be good to use. It's main benefit is that you can build it from the home directory with just `npm start`.

### CODE REVIEW

**Comment by yizongk** [comment]
in the main directory of boilerplate/
when I run npm install this error comes up:
> OSNY@0.0.1 start /home/yizongk/HunterCollege/OpenSourceWeiss/OpenSource-NY/src/boilerplate
> concurrently --kill-others-on-fail "cd client && npm start" "cd server && nodemon server.js"

[1] /bin/sh: 1: nodemon: not found


And according to the README, it looks like you still would have to go to boilderplate/server and boilerplate/client and do npm install on each of those directory before you can run the app. I am not sure how this can be built from home direcotry. Or do you mean you can run this from home directory with just npm start?

**Comment by yizongk** [comment]
It looks like we could imitate what you want from src/myapp/

By creating a package.json  in that directory and adding this 
"devDependencies": {
    "concurrently": "^3.6.1"
  }

and 

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "concurrently --kill-others-on-fail \"cd client && npm start\" \"cd server && npm start\""
  },

**Comment by yizongk** [comment]
Let me know anyones thoughts on this

**Comment by mxmsunny** [comment]
I went into boilerplate/server and boilerplate/client and followed the instructions that were written in the READMEs. I ran npm install for both of them, and ran npm start for the client, and this is what showed up on the website. Is it supposed to look like this?

osny

**Comment by mxmsunny** [comment]
> 
> 
> It looks like we could imitate what you want from src/myapp/
> 
> By creating a package.json in that directory and adding this
> "devDependencies": {
> "concurrently": "^3.6.1"
> }
> 
> and
> 
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1",
> "start": "concurrently --kill-others-on-fail "cd client && npm start" "cd server && npm start""
> },

@yizongk I don't think we have to run "npm start" in the server folder since it wasn't stated in the readme. However, I did try to run it, and I got an error "module.js:549 throw err;" It could just be on my end, though. Other than that, I'm fine with your changes!

**Comment by Chocolate-Spaghet** [comment]
@mxmsunny Yes, that's what it's supposed to show, since none of the content inside of the boilerplate was modified

**Comment by Chocolate-Spaghet** [comment]
@mxmsunny  Also, you only need to run `npm start` in the home directory (where the client directory and server directory are located) and that should start the client and server concurrently.

**Comment by Chocolate-Spaghet** [comment]
@yizongk I will add installation with one command script later on

**Comment by yizongk** [comment]
> @mxmsunny Also, you only need to run `npm start` in the home directory (where the client directory and server directory are located) and that should start the client and server concurrently.

That's the point that gave me the error that I mentioned in my first comment. 

Here's the command I did:
~~~
cd boilerplate/
npm install
cd client/
npm install
cd ../server/
npm install
cd ..               // At this point, my current directory is boilerplate/
npm start      // Give me error
~~~

image

**Comment by yizongk** [comment]
There is also so many other files and dependency, are they related to our project? or can they be removed?

**Comment by guti21js** [comment]
Since there seems to be an error experieced by two people I don't really think we should pull this request. I do think its a good start but the issue has to be tested on your side @Chocolate-Spaghet  to see if it occurs and then see if you can fix it.

**Review by guti21js — COMMENTED** [review]
Also had an error with npm start in the projct directory.

**Comment by Chocolate-Spaghet** [comment]
@yizongk do `npm i -g concurrently nodemon` in order to fix the error.

**Comment by yizongk** [comment]
You should add dependency to your package.json and update this PR

**Pull request closed without merging**
