### PR TITLE
Updated Styles and Component Reorganization 

### PR DESCRIPTION
**Pull request by Chocolate-Spaghet**
Hello!
In this pull request I have included all of your previous features, but I have rearranged the file system to make more sense.

### CODE REVIEW

**Comment by yizongk** [comment]
I think you should break this PR in to two PR. One only on the OpenSource-NY directory. Another one on the myapp direcotry. This repo's myapp directory has newer contents in it that fixes certain bugs, which is causing some merge conflict in your PR. 

some bugs that came up in your myapp directory crashes the website when I test it. Such as:

writing some gibberish in the input field like "sdfsdf/werewr" will crash the site when I submit:

image

I also think you should do smaller PR next time, so we can keep the process of Merging manageable. Because for this PR, I am not sure what a lot of the code changes have done to the overall function of the application, since we don't have extensive test sets for the front end or back end.

**Comment by yizongk** [comment]
I also think you should remove the npm install global for nodemon and concurrenly in the README. Since I see that you concurrenly in the OpenSource-NY/package.json, as well as nodemon in OpenSource-NY/server and client package.json. You don't have to include those install instructions in the README. Cuz it will all happen when you do npm install as part of setting up your working directory

**Comment by Chocolate-Spaghet** [comment]
This PR is not about the boilerplate, there I just changed a few things in the README and renamed the directory. This PR **is** about the reorganization done in the file structure. I'll fix the gibberish bug.

**Comment by yizongk** [comment]
So you are saying as of right now, the myapp and OpenSource-NY directory are an exact copy, function wise?

And your intend is to replace myapp with OpenSource-NY. Is this the purpose of this PR?

I won't be able to test it until it tonight

**Comment by yizongk** [comment]
Also the entering opensource-ny/OpenSource-NY into the input field results in "Error: opensource-ny/OpenSource-NY is invalid repository name."

Can you test out the input fields. 

what we got on the official repo checks for the following on the input field with input string S.
for S to be valid:
-must be of this form "soemthing/something". And only contain one slash.

For valid repos S:
-if no Pull Request exists, output some message about no data found on given repo
-if PR exists, output it in a list

**Comment by Chocolate-Spaghet** [comment]
I just checked, and it works.
Screen Shot 2019-03-26 at 3 51 03 PM

**Comment by yizongk** [comment]
Try this sequence: 
1. Enter some gibberish like "sdfwe/wer"
2. Enter "opensource-ny/OpenSource-NY"

I think somewhere in your code, you forgot to reset a boolean

**Comment by Chocolate-Spaghet** [comment]
Alright, I fixed the bugs and ignored the boilerplate (for now).
Please test @mxmsunny & @yizongk

**Comment by mxmsunny** [comment]
It looks good! But I think I have the same issue as Yi Zong had in the comment above. After I searched an invalid github repo, i.e www/www, and then search up a valid one, i.e this one, it shows that it is an invalid repository name. However, you can still search up the information of the valid one even though it says it's invalid, so I guess it's just a minor thing to fix.

test

**Comment by Chocolate-Spaghet** [comment]
@mxmsunny are you sure you got the updated version?
I just checked, and it works:
OSNY-ScreenRecording1Gif2

**Comment by yizongk** [comment]
I have the same error as sunny, but it's minor, and it's fixed in my current attempt to clear the merge conflict. will update soon

**Comment by yizongk** [comment]
Sort of fixes opensource-ny/OpenSource-NY#63  

Removes not only leading/trailing white spaces, but also white spaces in-between!

So a string such as "  ope   nsource-ny/OpenSo   urce-NY   " will be parsed as "opensource-ny.OpenSource-NY"  

Will need to fix this.

**Comment by yizongk** [comment]
Thanks for the organization, all previous bugs are flushed out. And now this PR contains the newer features of our main repo!

**Pull request merged**
